apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- guestbook-debug.yaml

images:
- name: alexmt/guestbook
  newName: alexmt/guestbook
  newTag: "0.1"
